apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "jellyfin.fullname" . }}
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-oauth2-proxy@kubernetescrd
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Services
    gethomepage.dev/name: jellyfin
    gethomepage.dev/description: Jellyfin
    gethomepage.dev/icon: sh-jellyfin.svg
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - {{ .Values.hostname }}
      secretName: {{ .Values.secretName }}
  rules:
    - host: {{ .Values.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "jellyfin.fullname" $ }}
                port:
                  number: 80
