# Kanidm minimal Service Configuration - /etc/kanidm/config
# For a full example and documentation, see /usr/share/kanidm/config
# or `example/kanidm` in the source repository.
uri = "https://sso.ncraig.dev"
verify_ca = true
