apiVersion: v2
name: prometheus
version: "0.0.0"
dependencies:
- name: kube-prometheus-stack
  version: 81.6.9
  repository: https://prometheus-community.github.io/helm-charts
- name: oauth2-proxy
  version: "10.1.4"
  repository: https://oauth2-proxy.github.io/manifests/
