apiVersion: v2
name: prometheus
version: "0.0.0"
dependencies:
- name: kube-prometheus-stack
  version: 80.14.4
  repository: https://prometheus-community.github.io/helm-charts
- name: oauth2-proxy
  version: "10.0.3"
  repository: https://oauth2-proxy.github.io/manifests/
