garage:
  deployment:
    replicaCount: 3

  persistence:
    meta:
      storageClass: longhorn
      size: 1Gi
    data:
      storageClass: longhorn-strict-local
      size: 12Gi

  monitoring:
    metrics:
      enabled: true

  garage:
    existingRpcSecret: garage-rpc-secret
